### ISSUE TITLE
Liquidator does not account for different asset decimals.

### ISSUE THREAD

**Issue by adrian-fjellberg** [flamingo-finance/flamingo-margin-maintainer#1]
I ran into an issue when trying to liquidate loans with fWETH as collateral. I noticed that the LTV calculation became incorrect because the F-asset and the collateral asset uses different decimal count. In my example FUSD uses 6 decimals and fWETH uses 18 decimals.

I think the culprit these lines of code:
https://github.com/flamingo-finance/flamingo-fusd-liquidator/blob/main/src/liquidator.ts#L89-L94
```ts
function computeLoanToValue(vault: AccountVaultBalance, priceData: PriceData) {
  const numerator = vault.fTokenBalance * priceData.fTokenPrice;
  if (numerator === 0) {
    return 0;
  }
  const denominator = vault.collateralBalance * priceData.collateralCombinedPrice;
  return (100 * numerator) / denominator;
}
```

The balances need to be adjusted for token decimals before they can be used in the calculations. I suggest creating a separate config file for the different assets defining how many decimals they have. We usually have file called `tokens.js` that defines a lot of static data about assets we use :)

**Comment by odd86** [comment]
@77696c6c Can this be set to solved?

**Comment by lyrebird-finance** [comment]
Yes, this has been addressed
